### ISSUE TITLE
Wrong (?) conversion factor from lsb to hpa

### ISSUE THREAD

**Issue by andrea-nistico** [STMicroelectronics/lps22hb-pid#1]
I have been using this driver for a bit now, in some older version, the conversion between lsband hpa was the following:
```
float_t lps22hb_from_lsb_to_hpa(int32_t lsb)
{
    return ((float_t)lsb / 4096.0f);
}
```
In the last release we have: 
```
float_t lps22hb_from_lsb_to_hpa(int32_t lsb)
{
    return ((float_t)lsb / 1048576.0f);
}
```
with the first scale factor, I get correct values but with the second the results are off. Where the ''1048576.0f'' comes from?

**Comment by albezanc** [comment]
Hi andrea,

In the latest version of the driver the `Press_raw_get` function exposes the data in uint32_t format left-aligned (not 24 bit), so an additional 8-bit shift is required: 4096.0f * 256 = 1048576.0f.

thanks for the opportunity for clarification

**Comment by andrea-nistico** [comment]
thanks for the answer, I solved with the following given your considerations:

```
typedef union {
    struct {
        uint32_t pressure32bit; /* pressure plus status register */
        int16_t temperature16bit;  /* temperature */
    } p_and_t;
    uint8_t u8bit[FIFO_DATA_SAMPLE_LEN];
} p_and_t_byte_t;

void hub_fifo_baro_axis_read(float_t *axis) {
    static p_and_t_byte_t axisRaw;
    lsm6dsox_fifo_out_raw_get(hub_ctx_ptr, axisRaw.u8bit);
    axisRaw.p_and_t.pressure32bit <<= 8; // left byte shift for correct value 
    *axis = lps22hb_from_lsb_to_hpa(axisRaw.p_and_t.pressure32bit);
}
```

I haven't noticed the change since I am using fifo_raw_get with sensor hub which is different, thanks! Maybe it is worth mentioning this in the sensor hub examples?

**Comment by ChulseungYoo** [comment]
```
/**
  * @brief  Pressure output value[get]
  *
  * @param  ctx    Read / write interface definitions
  * @param  buff   Buffer that stores data read
  * @retval        Interface status (MANDATORY: return 0 -> no Error).
  *
  */
int32_t lps22hb_pressure_raw_get(const stmdev_ctx_t *ctx, uint32_t *buff)
{
  uint8_t reg[3];
  int32_t ret;

  ret =  lps22hb_read_reg(ctx, LPS22HB_PRESS_OUT_XL, reg, 3);
  *buff = reg[2];
  *buff = (*buff * 256) + reg[1];
  *buff = (*buff * 256) + reg[0];
  *buff *= 256;

  return ret;
}
```
```

/**
  * @defgroup    LPS22HB_FIFO_Output_Data
  * @brief       These functions convert FIFO output data to seperate
  *              (pressure, temperautre) fields.
  * @{
  *
  */

int32_t lps22hb_fifo_output_data_to_raw_pressure(lps22hb_fifo_output_data_t *val)
{
  int32_t pressure = val->bytes[2];
  pressure = (pressure * 256) + val->bytes[1];
  return (pressure * 256) + val->bytes[0];
}
```

HI @albezanc 
There are still some issues remaining. 
Currently, the lps22hb_from_lsb_to_hpa function has reverted to the previous method of dividing by 4096. 
However, the lps22hb_fifo_output_data_to_raw_pressure part is fine without the 8-bit shift, while the code in lps22hb_pressure_raw_get is still performing the 8-bit shift.
The results from these two functions should be the same, but they are coming out differently. 
It might be advisable to remove the 8-bit shift code from lps22hb_pressure_raw_get for consistency.
